### PR TITLE
Replace progress slider with number spinner

### LINKED ISSUE #1913: Logging games, analysis and retros above the goal TECHGEN#346
**💬 Content:** 
  > When trying to log games played, post mortems, and game analysis over the total goal number (e.g 50 games per year). the Increment up arrow button does not work. I have to delete the previous number and type in the new number.  I don't care about th goal of 50.  I just want to log my classical games played, post mortems and analysis performed. Instead of an increments arrow, allow me to log the number of games played, reviewed or postmortemed with a default value of 1.

👤 Author name: KenpoGMBrian
[Discord URL](https://discord.com/channels/951958534113886238/1026952329804644372/1460476267513254093)

### PR DESCRIPTION
**Pull request by Dblike**
## Summary
Closes #1913

- Added a new `NumberSpinner` component with decrement/increment buttons and a centered numeric input
- Replaced the `InputSlider` (slider + text field) in `ProgressUpdater` with the new `NumberSpinner`
- Removed the max count constraint so users can increment past the target count

## Test plan
- [ ] Open a ProgressBar task (e.g. "Read Simple Chess" with Pages suffix) and verify the +/- spinner appears
- [ ] Verify decrement is disabled at the min value
- [ ] Verify the input accepts typed numbers and clamps to min on blur
- [ ] Verify Unspecified display type tasks also show the spinner
- [ ] Verify Checkbox, Minutes, and NonDojo tasks are unaffected

image

### CODE REVIEW

**Review by jackstenglein — CHANGES_REQUESTED** [review]
@Dblike Does this remove the slider as well? Sorry, I guess I should have been more specific in the issue description. We would like to keep the slider, but also have the increment/decrement buttons next to the textfield. In your screenshot, would you mind showing the full dialog?

File: frontend/src/components/profile/trainingPlan/InputSlider.tsx [hunk 1]
```diff
@@ -9,6 +12,12 @@ interface InputSliderProps {
 }
 
 const InputSlider: React.FC<InputSliderProps> = ({ value, setValue, max, min, suffix }) => {
+    useEffect(() => {
+        if (value < min) {
+            setValue(min);
+        }
+    }, []);
```
Comment (jackstenglein) [inline frontend/src/components/profile/trainingPlan/InputSlider.tsx]: Shouldn't this have both value, min and setValue in the dependency array?
