### PR TITLE
fix: allow user to hide/open weekly view

### LINKED ISSUE #1957: Allow users to hide weekly view
Allow users to hide/unhide the weekly view of their tasks

### PR DESCRIPTION
**Pull request by jalpp**
fixes #1957

### CODE REVIEW

File: frontend/src/components/profile/trainingPlan/weekly/WeeklyTrainingPlan.tsx [hunk 1]
```diff
@@ -26,6 +38,8 @@ export function WeeklyTrainingPlan() {
         timeline,
     });
 
+    const [expanded, setExpanded] = useState<boolean>(true);
```
Comment (jackstenglein) [inline frontend/src/components/profile/trainingPlan/weekly/WeeklyTrainingPlan.tsx]: We should remember whether the user has collapsed the weekly view or not

**Review by jackstenglein — CHANGES_REQUESTED** [review]

**Review by jackstenglein — APPROVED** [review]
