### PR TITLE
fix(activity): fix other user editing activity bug

### LINKED ISSUE #1384: Apparently can edit other's activity? Tech_BUG#980
**📓 Steps to reproduce:** 
  > 1. click on follower or follows  from training plan page
2. after landing on their training page, click activities
3.  there is a pencil icon (edit activity) - click this
4. you apparently can edit activities that are not your own.  (note, I didn't confirm I could edit another's activity but it sure seems you can) 
The edit activity icon / action should not be present on someone else's activity.
🔨 Platform: chessdojo.club
📱 Device Type: Desktop
🌐 Browser Type: Chrome 34.0.6998.118 on OSX

👤 Author name: blueguitargambit
[Discord URL](https://discord.com/channels/951958534113886238/1299913797045325957/1359221627824373984)

### PR DESCRIPTION
**Pull request by jalpp**
fixes #1384

### CODE REVIEW

File: frontend/src/components/newsfeed/NewsfeedItem.tsx [hunk 1]
```diff
@@ -17,15 +19,20 @@ interface NewsfeedItemProps {
...
     onChangeActivity?: (entry: TimelineEntry) => void;
+    currentUser?: User;
 }
 
 const NewsfeedItem: React.FC<NewsfeedItemProps> = ({
     entry,
     onEdit,
     maxComments,
     onChangeActivity,
+    currentUser,
```
Comment (jackstenglein) [inline frontend/src/components/newsfeed/NewsfeedItem.tsx:30]: Rather than adding a new prop, could we just check against `entry.owner`?

**Review by jackstenglein — APPROVED** [review]
